# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FedLearningProto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x46\x65\x64LearningProto.proto\"B\n\x13RegistrationRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x11\n\tclient_id\x18\x03 \x01(\x05\"H\n\x14RegistrationResponse\x12\x19\n\x11\x63onfirmation_code\x18\x01 \x01(\x05\x12\x15\n\rcurrent_round\x18\x02 \x01(\x05\"H\n\x14TrainingStartRequest\x12\x15\n\rcurrent_round\x18\x01 \x01(\x05\x12\x19\n\x11weights_file_path\x18\x02 \x01(\t\"1\n\x10TrainingResponse\x12\x1d\n\x15local_dataset_samples\x18\x01 \x01(\x05\"9\n\x11\x45valuationRequest\x12$\n\x1c\x61ggregated_weights_file_path\x18\x01 \x01(\t\"&\n\x12\x45valuationResponse\x12\x10\n\x08\x61\x63\x63uracy\x18\x01 \x01(\x02\x32O\n\x0eTrainingServer\x12=\n\x0eRegisterClient\x12\x14.RegistrationRequest\x1a\x15.RegistrationResponse2\x87\x01\n\x0eTrainingClient\x12;\n\rStartTraining\x12\x15.TrainingStartRequest\x1a\x11.TrainingResponse0\x01\x12\x38\n\rEvaluateModel\x12\x12.EvaluationRequest\x1a\x13.EvaluationResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FedLearningProto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTRATIONREQUEST._serialized_start=26
  _REGISTRATIONREQUEST._serialized_end=92
  _REGISTRATIONRESPONSE._serialized_start=94
  _REGISTRATIONRESPONSE._serialized_end=166
  _TRAININGSTARTREQUEST._serialized_start=168
  _TRAININGSTARTREQUEST._serialized_end=240
  _TRAININGRESPONSE._serialized_start=242
  _TRAININGRESPONSE._serialized_end=291
  _EVALUATIONREQUEST._serialized_start=293
  _EVALUATIONREQUEST._serialized_end=350
  _EVALUATIONRESPONSE._serialized_start=352
  _EVALUATIONRESPONSE._serialized_end=390
  _TRAININGSERVER._serialized_start=392
  _TRAININGSERVER._serialized_end=471
  _TRAININGCLIENT._serialized_start=474
  _TRAININGCLIENT._serialized_end=609
# @@protoc_insertion_point(module_scope)
